### PR TITLE
improve typescript 

### PR DESCRIPTION
**Pull request by budet-b**
Hello, when working on this SDK I noticed few type errors and missing types for Hooks. This PR fix them and strong types all payload according to your documentation https://developers.screeb.app/sdk-react-native/react-native-hooks 

Hope it helps!

### CODE REVIEW

**Comment by budet-b** [comment]
@Alexays Hello, do you have time to review this PR in comings days? we can also pair-review if needed

**Comment by Alexays** [comment]
Hi, thx for the PR :) 
Can you just remove type about hooks name and hooks payload → <string, object>
As we have several SDKs, if we change something or add a new hook, we have to update all these SDKs.
That's why we tend to say that the source of truth is our doc here https://developers.screeb.app/sdk-react-native/react-native-hooks

**Comment by louiszawadzki** [comment]
Hi @Alexays 👋 
I'm a coworker of @budet-b :) 
We'd like to understand a bit more the context around the hooks. 

From what I understand, today when changing/adding a hook you still have to add/change code in the SDKs and release them, is that correct?

**Comment by louiszawadzki** [comment]
Hi @Alexays :) 

Bumping this discussion, could you explain what you mean by "if we change something or add a new hook, we have to update all these SDKs"? 
Do you mean that adding hooks can be added/changed without updating the SDKs? If this is the case we need to ensure backward compatibility in our apps as our users can sometimes use an old version, do you have processes to make sure we don't break old versions and would you recommend to wrap all our calls to the SDK by `try`/`catch` blocks to prevent our app from crashing because of Screeb?

Thanks a lot!

**Comment by Alexays** [comment]
Hi, really sorry for the delay @louiszawadzki.
Our hooks are versioned using the `version` key.
Unless we do breaking change on existing hooks, we'll not bump this version.
And so, we can add new hooks without the need to update all the SDKs as not a breaking change.

**Pull request closed without merging**
